[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
storymode = false
storymodemethod = 1
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0

[settings.background]
background_video = "stock"
background_audio = "lofi"
background_audio_volume = 0.0
enable_extra_audio = false
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "elevenlabs"
random_voice = true
elevenlabs_voice_name = "Adam"
elevenlabs_api_key = "f04d61035663233275b542d11930ecad"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = "449976dc92e41daae8370be3a1649986"
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

[reddit.creds]
client_id = "wBYK-XaGrThXZypBa3EIGg"
client_secret = "m-5VAI6K4nRSIXIovQ8jXjNd4kRMtg"
username = "vikitwenty"
password = "Viki@8968"
2fa = false

[reddit.thread]
random = true
subreddit = "AskMen"
post_id = "18leu8l"
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20
